name: express-app

on:
  push:
    branches:
      - main
    paths:
      - "express-app/**"
      - ".github/workflows/express-app.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: "express-app"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          node-version: "16"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies
        run: npm install

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push express-app
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: siddarthal/githubactions:latest
